#!/bin/sh

echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Pictures</title>
  </head>
  <body>
  <h1>Pictures</h1>'
if [ $# -gt 0 ]
then # check if the colum is integers and greater than 0
  if `echo $1 | grep -q "^[0-9]*$"` && [ $1 -gt 0 ]
  then # check if theres a second argument 
    if [ $# -gt 1 ]
    then # check if the second argument is a directory
      col=$1
      if [ -d $2 ]
      then # loop through each year and check if it a directory
        for year in $2/*
        do
          if [ -d $year ]
          then
            echo "<h2>`basename $year`</h2>"
            echo "<table>"
            count=0 # loop through each month and check if it a directory
            for month in $year/*
            do
              if [ -d $month ]
              then # loop through each pictures and check if is a jpg file
              	for pic in $month/*
              	do
                  if file $pic | grep -q JPEG;
                  then
              	    if [ $count -eq 0 ]
              	    then
              	      echo "<tr>"
              	    fi # if count is less than column then add a new td in that row
              	    if [ $count -lt $col ]
              	    then
              	  	  echo "<td><img src=\"$pic\" height=100></td>"
                      count=`expr $count + 1`
                    else # otherwise open a new row and continue
                	    echo "</tr>"
                      echo "<tr>"
                      echo "<td><img src=\"$pic\" height=100></td>"
                	    count=1
         		        fi
                  else # prints when pic is not a jpg or is empty
                      echo "$pic is not a JPEG file or is empty.">&2
                  fi
                done
              else # prints when month is not a directory or is empty
                echo "$month is not a directory or $year is empty">&2
              fi
            done # check and close tr and table
            if [ $count -ne 0 ]
    	      then
      		    echo "</tr>"
    		    fi
            echo "</table>"	
          else # prints when year is not directory
            echo "$year is not a directory">&2 
          fi
        done 
      else # prints when the second argument is not directory
  	    echo "$2 is not a directory">&2
      fi
    else # prints when there is only one argument passes
      echo "Missing a Directory">&2
    fi
  else # prints when the first argument is invalid
    echo "Invalid input">&2    
  fi
else # prints when no arguments in passed
  echo "No arguments passed">&2
fi
echo "</body> </html>"